In [8]:
import pandas as pd

In [9]:
std_data_path = "download.csv"

In [10]:
std_data = pd.read_csv(std_data_path)

In [11]:
std_data = std_data.iloc[:,1:]

In [12]:
std_data

,Username,Email,Classroom,Language,Streak,Days active,Total XP,Time Spent Learning,Ramp Up Challenge,Lessons,Level Review,Writing,Practice,Stories,Legendary,Other
0,Da_joker360,realatm360@gmail.com,Premium Class,Arabic,0,4,3004,2h 1m,31,21,4,0,0,0,0,1
1,FaroukMusa1,faroukmusatukur@gmail.com,Premium Class,Spanish,0,101,7083,10h 24m,145,50,12,0,7,10,4,1
2,Yipmong2020,said2@schools.duolingo.com,Premium Class,Arabic,0,0,0,0h 0m,0,0,0,0,0,0,0,0
3,Syed_Hassaan_420,syedhassaan720@gmail.com,Premium Class,Arabic,162,97,14049,13h 34m,135,142,28,85,1,0,14,1
4,WalterTron3,waltertronics02@gmail.com,Premium Class,German,122,31,7941,6h 49m,44,73,20,0,21,18,0,6
5,Waltertron6,Waltertron6@schools.duolingo.com,Premium Class,English,0,0,0,0h 0m,0,0,0,0,0,0,0,0
6,Yipmong,syipmong5@gmail.com,Premium Class,NaN,286,221,168136,73h 45m,2287,294,65,8,58,2,6,1
7,fayalicha,learn.informatique7@gmail.com,Premium Class,English,0,0,0,0h 0m,0,0,0,0,0,0,0,0
8,lazypillow3,successp50001@gmail.com,Premium Class,Spanish,0,20,1229,1h 58m,26,14,4,0,2,0,0,1